version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.2.2
